# External Secrets Operator - Sync secrets from external providers
# https://external-secrets.io

enabled: true

chart:
  repository: https://charts.external-secrets.io
  name: external-secrets
  version: "" # Latest

release:
  name: external-secrets
  namespace: external-secrets

ingress:
  enabled: false

values:
  installCRDs: true

  resources:
    requests:
      cpu: "10m"
      memory: "64Mi"
    limits:
      cpu: "100m"
      memory: "128Mi"

  webhook:
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "50m"
        memory: "64Mi"

  certController:
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "50m"
        memory: "64Mi"

  serviceMonitor:
    enabled: false

postInstall: |
  ---
  apiVersion: operator.victoriametrics.com/v1beta1
  kind: VMPodScrape
  metadata:
    name: external-secrets
    namespace: external-secrets
    labels:
      release: vm
  spec:
    podMetricsEndpoints:
      - port: metrics
        path: /metrics
    selector:
      matchLabels:
        app.kubernetes.io/name: external-secrets
