#!/bin/bash
# Show all service connection URLs and credentials

DOMAIN="${DOMAIN:-minikube.local}"

# Try to get actual PostgreSQL credentials from cluster
PG_USER="app"
PG_DB="app"
PG_PASS=""
if command -v kubectl &> /dev/null; then
    PG_PASS=$(kubectl get secret postgresql-cluster-app -n postgresql -o jsonpath='{.data.password}' 2>/dev/null | base64 -d 2>/dev/null)
fi
if [ -z "$PG_PASS" ]; then
    PG_PASS="<run 'kubectl get secret postgresql-cluster-app -n postgresql -o jsonpath=\"{.data.password}\" | base64 -d'>"
fi

echo "============================================"
echo "  Service Connection Details"
echo "============================================"
echo ""
echo "Domain: *.$DOMAIN"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  PostgreSQL (CloudNativePG)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Read-Write:"
echo "  Host:     postgresql.$DOMAIN"
echo "  Port:     5432"
echo "  Database: $PG_DB"
echo "  Username: $PG_USER"
echo "  Password: $PG_PASS"
echo ""
echo "  URL:      postgresql://$PG_USER:<password>@postgresql.$DOMAIN:5432/$PG_DB"
echo "  JDBC:     jdbc:postgresql://postgresql.$DOMAIN:5432/$PG_DB"
echo ""
echo "Read-Only Replica:"
echo "  Host:     postgresql.$DOMAIN"
echo "  Port:     5433"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Redis"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Host:     redis.$DOMAIN"
echo "  Port:     6379"
echo "  Password: LocalDev123!"
echo ""
echo "  URL:      redis://:LocalDev123!@redis.$DOMAIN:6379"
echo "  CLI:      redis-cli -h redis.$DOMAIN -p 6379 -a 'LocalDev123!'"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  NATS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Host:      nats.$DOMAIN"
echo "  Port:      4222"
echo "  Auth:      none (local dev)"
echo ""
echo "  URL:       nats://nats.$DOMAIN:4222"
echo "  Dashboard: https://dashboard.nats.$DOMAIN"
echo "  Monitor:   https://monitoring.nats.$DOMAIN"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  OpenSearch"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  URL:      https://opensearch.opensearch.$DOMAIN"
echo "  Username: admin"
echo "  Password: LocalDev123!"
echo ""
echo "  Dashboards: https://dashboards.opensearch.$DOMAIN"
echo ""
echo "  curl:     curl -k -u admin:LocalDev123! https://opensearch.opensearch.$DOMAIN"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Grafana (VictoriaMetrics)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  URL:      https://grafana.monitoring.$DOMAIN"
echo "  Username: admin"
echo "  Password: LocalDev123!"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ArgoCD"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  URL:      https://console.argocd.$DOMAIN"
echo ""
echo "  SSO Login (via Dex):"
echo "    Admin:     admin@$DOMAIN / admin123"
echo "    Developer: developer@$DOMAIN / dev123"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Dex (SSO Provider)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  URL:      https://auth.dex.$DOMAIN"
echo ""
echo "  Static Users:"
echo "    admin@$DOMAIN     / admin123   (admin role)"
echo "    developer@$DOMAIN / dev123     (readonly role)"
echo ""

echo "============================================"
echo "  Environment Variables (copy-paste ready)"
echo "============================================"
echo ""
echo "# PostgreSQL"
echo "export DATABASE_URL=\"postgresql://$PG_USER:<password>@postgresql.$DOMAIN:5432/$PG_DB\""
echo "export PGHOST=\"postgresql.$DOMAIN\""
echo "export PGPORT=\"5432\""
echo "export PGDATABASE=\"$PG_DB\""
echo "export PGUSER=\"$PG_USER\""
echo "export PGPASSWORD=\"$PG_PASS\""
echo ""
echo "# Redis"
echo "export REDIS_URL=\"redis://:LocalDev123!@redis.$DOMAIN:6379\""
echo "export REDIS_HOST=\"redis.$DOMAIN\""
echo "export REDIS_PORT=\"6379\""
echo "export REDIS_PASSWORD=\"LocalDev123!\""
echo ""
echo "# NATS"
echo "export NATS_URL=\"nats://nats.$DOMAIN:4222\""
echo "export NATS_HOST=\"nats.$DOMAIN\""
echo "export NATS_PORT=\"4222\""
echo ""
echo "# OpenSearch"
echo "export OPENSEARCH_URL=\"https://opensearch.opensearch.$DOMAIN\""
echo "export OPENSEARCH_USERNAME=\"admin\""
echo "export OPENSEARCH_PASSWORD=\"LocalDev123!\""
echo ""

echo "============================================"
echo "  Docker Compose Integration"
echo "============================================"
echo ""
echo "To use these services from Docker Compose:"
echo ""
echo "1. Run in separate terminals:"
echo "   make tunnel        # Exposes services to host"
echo "   make docker-bridge # Bridges to Docker network"
echo ""
echo "2. Add extra_hosts to your services:"
echo "   make docker-hosts  # Shows the snippet to copy"
echo "   make docker-patch FILE=./docker-compose.yml  # Auto-patch"
echo ""
